namespace ShopFish.Migrations
{
    using ShopFish.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using System.Web.Helpers;
    internal sealed class Configuration : DbMigrationsConfiguration<ShopDatabaseContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            AutomaticMigrationDataLossAllowed = true;
            ContextKey = "ShopFish.ShopDatabaseContext";
        }

        protected override void Seed(ShopDatabaseContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.
        //    List<Role> roles = new List<Roles>()
        //    {
        //        new Role() { Name = "User"},
        //        new Role() {  Name = "Admin"}
        //    };

        //    List<Roles> rolesDb = new List<Roles>();
        //    foreach (var role in roles)
        //    {
        //        rolesDb.Add(context.Roles.Add(role));
        //    }
        //    Accounts taikhoan_1 = new Accounts()
        //    {
        //        Usernames = "abc",
        //        Passwords = Crypto.HashPassword("123"),
        //        NameUser = "Nguyễn Thành Lộc",
        //        Gender = "Nam",

        //        Tel = "1234567890",
        //        Addresss = "asdasdsa",
        //        email = "maquydoi2@gmail.com",
        //        IDRole = 1,
        //        createsdate = DateTime.Now,
        //        Roles = rolesDb.Last()
        //    };
        //    Accounts taikhoan_2 = new Accounts()
        //    {
        //        Usernames = "loc",
        //        Passwords = Crypto.HashPassword("123"),
        //        NameUser = "Nguyễn Thành Lộc",
        //        Gender = "Nam",

        //        Tel = "1234567890",
        //        Addresss = "asdasdsa",
        //        email = "maquydoi0@gmail.com",
        //        IDRole = 2,
        //        createsdate = DateTime.Now,
        //        Roles = rolesDb.First()
        //    };

        //    context.Accounts.Add(taikhoan_1);
        //    context.Accounts.Add(taikhoan_2);

        //    Categories a = new Categories();
        //    a.Name = "Cá Cầu Vồng";
        //    a.Type = "Fish";
        //    Categories b = new Categories();
        //    b.Name = "Cá Vàng Lan Thọ";
        //    b.Type = "Fish";
        //    Categories c = new Categories();
        //    c.Name = "Cá Đĩa";
        //    c.Type = "Fish";
        //    Categories d = new Categories();
        //    d.Name = "Cá La Hán";
        //    d.Type = "Fish";
        //    Categories e = new Categories();
        //    e.Name = "Cá Rồng";
        //    e.Type = "Fish";
        //    Categories ee = new Categories();
        //    ee.Name = "Loại cá khác";
        //    ee.Type = "Fish";
        //    Categories f = new Categories();
        //    f.Name = "Thức ăn cho cá";
        //    f.Type = "Food";
        //    Categories g = new Categories();
        //    g.Name = "Bể cá để bàn";
        //    g.Type = "aquarium";
        //    Categories h = new Categories();
        //    h.Name = "Bể cá treo tường";
        //    h.Type = "aquarium";
        //    Categories i = new Categories();
        //    i.Name = "Bể cá phong thuỷ";
        //    i.Type = "aquarium";
        //    Categories k = new Categories();
        //    k.Name = "Bể cá chân tủ gỗ";
        //    k.Type = "aquarium";
        //    Categories l = new Categories();
        //    l.Name = "Bể cá mini";
        //    l.Type = "aquarium";
        //    Suppliers aa = new Suppliers();
        //    aa.Name = "Thiên Đường Cá Cảnh";
        //    Suppliers bb = new Suppliers();
        //    bb.Name = "Vua cá cảnh";
        //    Suppliers cc = new Suppliers();
        //    cc.Name = "AquaZone";
        //    List<Products> products = new List<Products>()
        //    {
        //         new Products(){Product_Code="CCV", Name="Banded", Image = "banded.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000,Hot="Hot", Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = a, Suppliers = aa},
        //         new Products(){Product_Code="CCV", Name="Bleher's", Image = "bleher's.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Hot="Hot", Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = a, Suppliers = aa},
        //         new Products(){Product_Code="CCV", Name="Boeseman's", Image = "boeseman's.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = a, Suppliers = bb},
        //         new Products(){Product_Code="CCV", Name="Celebes's", Image = "celebes's.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = a, Suppliers = bb},
        //         new Products(){Product_Code="CCV", Name="Dwarf neon", Image = "dwarf neon.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = a, Suppliers = bb},
        //         new Products(){Product_Code="CCV", Name="Forktail blue-eye", Image = "forktail blue-eye.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = a, Suppliers = bb},

        //           new Products(){Product_Code="LT", Name="Cá vàng Shubunkin", Image = "ca-vang-shubunkin-23.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = b, Suppliers = aa},
        //         new Products(){Product_Code="LT", Name="Cá Vàng Thường", Image = "CaVangThuong.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = b, Suppliers = aa},
        //         new Products(){Product_Code="LT", Name="Cá Vàng Đầu Lân", Image = "daulan.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = b, Suppliers = bb},
        //         new Products(){Product_Code="LT", Name="Cá Hạc Đỉnh Hồng", Image = "hacdinhhong.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = b, Suppliers = bb},
        //         new Products(){Product_Code="LT", Name="Cá Ngọc Trai", Image = "ngoctrai.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = b, Suppliers = bb},
        //         new Products(){Product_Code="LT", Name="Cá Sao Chổi", Image = "saochoi.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = b, Suppliers = bb},

        //        new Products(){Product_Code="CD", Name="Cá đĩa Xanh lá", Image = "Xanh.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = c, Suppliers = aa},
        //         new Products(){Product_Code="CD", Name="Cá đĩa Xanh", Image = "Diamond.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = c, Suppliers = aa},

        //           new Products(){Product_Code="CLH", Name="Tân King", Image = "Ca Tan King.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 ,Hot="Hot", Categories = d, Suppliers = aa},
        //         new Products(){Product_Code="CLH", Name="Hán Kim Cương", Image = "ca-la-han-kim-cuong.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 ,Hot="Hot", Categories = d, Suppliers = aa},
        //         new Products(){Product_Code="CLH", Name="King Kamfa", Image = "ca-la-han-king-kamfa.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = d, Suppliers = bb},
        //         new Products(){Product_Code="CLH",Hot="Hot", Name="Thái Đỏ", Image = "ca-la-han-thai-do.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = d, Suppliers = bb},
        //         new Products(){Product_Code="CLH", Name="FHstrain_FP2", Image = "FHstrain_FP2.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = d, Suppliers = cc},
        //         new Products(){Product_Code="CLH", Name="Thaisilk", Image = "Thaisilk.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = d, Suppliers = cc},

        //           new Products(){Product_Code="CR", Name="Châu Phi", Image = "ca rong chau phi.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 0,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = e, Suppliers = aa},
        //         new Products(){Product_Code="CR", Name="Đỏ ớt", Image = "ca rong do ot.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = e, Suppliers = aa},
        //         new Products(){Product_Code="CR", Name="Hắc Long", Image = "ca rong hac long.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = e, Suppliers = bb},
        //         new Products(){Product_Code="CR", Name="Ngân Long", Image = "Ca rong ngan long.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 ,Hot="Hot", Categories = e, Suppliers = bb},
        //         new Products(){Product_Code="CR", Name="Huyết Long", Image = "HuyetLong.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = e, Suppliers = cc},
        //         new Products(){Product_Code="CR", Name="Thanh Long", Image = "Thanh Long.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = e, Suppliers = cc},

        //         new Products(){Product_Code="LK", Name="Cá Chép Koi", Image = "ca chep Koi.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = ee, Suppliers = aa},
        //         new Products(){Product_Code="LK", Name="Cá thiên thần lửa", Image = "ca thien than lua.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0,Hot="Hot" , Categories = ee, Suppliers = aa},
        //         new Products(){Product_Code="LK", Name="Cá thù lù", Image = "ca thu lu.jpg", Descriptions="Là một loài cá phía tây Đại Tây Dương,Massachusetts nam Brazil trong đó có Vịnh Mexico và vùng biển Caribê. Nó cũng được tìm thấy ở phía đông trung tâm Đại Tây Dương.",
        //            LivingEnvironment="Là một loài cá sống đơn độc hoặc theo cặp.Chúng sống ở các vùng nước nông gần rạn san hô.Nó là một loài cá hoạt động vào ban ngày và ngủ vào ban đêm.Vào cuối ngày chúng thường tìm nơi trú ẩn để tránh những kẻ săn mồi vào ban đêm như lươn biển,cá mập và một số loại cá lớn khác." ,
        //            GeneralFeatures="Có hình dạng mỏng,khá giống cá dĩa.Cơ thể chúng có những khả năng đặc biệt,giúp chúng có thể bơi đường dài.Vây lưng có gai nổi bật về phía trước.Trán của nó khá lõm. Những con cá chưa trưởng thành thường có sự khác biệt.Chúng có nhiều sọc trên cơ thể,màu sắc tổng thể là màu vàng nâu thay vì màu trắng.Chúng thường lẩn trốn trong các rạn san hô,rong biển.Vì vậy,màu sắc cơ thể giúp chúng nguy trang.Sọc đầu tiên chạy qua mắt gây nhầm lẫn như chúng là một động vật ăn thịt",
        //             Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = ee, Suppliers = bb},

        //        new Products(){Product_Code="TACC", Name="Artemia Sấy Khô", Image = "Artemia.jpg", Descriptions="Artemia tách vỏ đã được khử trùng, nhưng vẫn giữ được hàm lượng dinh dưỡng cao, rất tiện lợi khi bạn không có thời gian sử dụng loại ấp nở. Hướng dẫn sử dụng: dùng được ngay mà không cần ấp. Bảo quản: nơi thoáng mát, tốt nhất đặt ở ngăn mát tủ lạnh.",
        //            LivingEnvironment="",GeneralFeatures="",Hot="", Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = f, Suppliers = aa},

        //        new Products(){Product_Code="TACC", Name="Thức ăn Sapphire (độ đạm 46%)", Image = "Sapphire.jpg", Descriptions="Sapphire là sản phẩm cao cấp dành cho cá con, cá nhỏ, cá thủy sinh với độ đạm 46%.Dùng cho cá Betta, Neon, guppy, cichlid, mũi đỏ, tam giác, bảy màu, chuột thái, hồng mi, công gô, cánh bườm,...Tăng màu sắc và giúp cá mau lớn.Giàu vitamin và enzyme giúp cá dễ tiêu hóa.Sản phẩm không làm đục nước.",
        //            LivingEnvironment="",GeneralFeatures="",Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0,Hot="Hot" , Categories = f, Suppliers = bb},

        //        new Products(){Product_Code="TACC", Name="FWUSOWKOI", Image = "FWUSOWKOI.jpg", Descriptions="Fwusow Koi Food là thức ăn giúp cá tăng trưởng và tăng màu tươi sáng cho cá Koi.Với công thức đặc biệt giúp cho Koi có nguồn dinh dưỡng cân bằng, cá lớn nhanh nhưng vẫn giữ được sự thon thả và năng động của Koi. Thành phần có chứa tảo Spirulina, Krill meal giúp màu sắc tươi sáng và đậm màu. Độ đạm cao >=38%, tiết kiệm chi phí thức ăn. Dễ tiêu hóa. Là thức ăn nổi, không gây ô nhiễm nguồn nước.",
        //             LivingEnvironment="",GeneralFeatures="",Hot="",    Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = f, Suppliers = cc},

        //           new Products(){Product_Code="BC", Name="Hồ cá mini", Image = "ho-ca-mini-40-6-300x300.jpg", Descriptions="Hồ mini 40x20x22 cm (kính 5ly, chân mica). Lọc treo Sobo, Jebo, Up Aqua. Đèn led kẹp, led gác Đồ trang trí: cây, cát, đá màu, đá thủy tinh, núi đá nhân tạo",
        //          LivingEnvironment="",GeneralFeatures="", Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0,Hot="Hot" , Categories = g, Suppliers = bb},


        //               new Products(){Product_Code="BC", Name="Hồ treo tường cảnh biển", Image = "ho-treo-tuong-canh-bien-7.jpg", Descriptions="bể cá treo tường giúp tiết kiệm không gian vì được thiết kế nhỏ gọn, dễ di chuyển, năng động trong việc bố trí. Ngoài ra, chúng còn được sử dụng kết hợp với các trang trí khác có thể ngăn chia không gian, điều chỉnh và cân bằng phong thủy trong nhà.",
        //              LivingEnvironment="",GeneralFeatures="",    Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0,Hot="Hot" , Categories = h, Suppliers = bb},

        //        new Products(){Product_Code="BC", Name="Bể thủy sinh", Image = "be-thuy-sinh-2014-25.jpg", Descriptions="Một bể thủy sinh đẹp được gia công cẩn thận từ ngoài vào trong. Một bể thuỷ sinh với những thiết bị Lọc nước – Chiếu sáng – CO2 – Chiller cao cấp nhất trên thị trường. Một bể thuỷ sinh phù hợp với thẩm mỹ và khả năng chăm sóc của gia chủ. Đem tới sự thoải mái thực sự của một thú chơi!",
        //           LivingEnvironment="",GeneralFeatures="",     Quanlity = 10,Price = 65000, Createdates = DateTime.Now, Datesupdate = DateTime.Now,viewcount = 0 , Categories = h, Suppliers = cc},

        //    };
        //    List<Products> ProductsAfterInsert = new List<Products>();
        //    foreach (var product in products)
        //    {
        //        ProductsAfterInsert.Add(context.Products.Add(product));
        //    }
        //    TypeBlog m = new TypeBlog();
        //    m.Name = "Chăm sóc cá cảnh";

        //    TypeBlog n = new TypeBlog();
        //    n.Name = "Trang trí hồ cá";

        //    TypeBlog p = new TypeBlog();
        //    p.Name = "Thức ăn tốt cho cá";
        //    List<Blog> blogs = new List<Blog>()
        //    {
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //       Type = "Hoca",
        //        TypeBlogs = n

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //        Type = "Hoca",
        //        TypeBlogs = n

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",

        //          Type = "Hoca",
        //        TypeBlogs = n

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //      Type = "Fish",
        //        TypeBlogs = m

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //          Type = "Thucan",
        //        TypeBlogs = p

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //          Type = "Thucan",
        //        TypeBlogs = p

        //    },

        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //            Type = "Fish",
        //        TypeBlogs = m

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //           Type = "Hoca",
        //        TypeBlogs = n

        //    },
        //    new Blog()
        //    {
        //        Title = "Cách diệt rêu tảo hại trong hồ cá đơn giản hiệu quả",
        //        CreateDay = DateTime.Now,
        //        image1 = "cach-diet-reu-tao-hai-trong-ho-ca.jpg",
        //        HeadBlog = "Cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh ăn rêu tảo thực sự là một lựa chọn tuyệt vời cho bể cá cảnh hay bể thủy sinh. Không những làm cho hồ của bạn thêm sinh động mà còn có khả năng giúp bạn kiểm soát và giảm bớt các loại rêu tảo có hại. Hãy thử xem chúng là những loài nào và bạn đã biết cách kết hợp những loài sinh vật cảnh này với các loại tảo thích hợp hay chưa nhé!",
        //        BodyBlog = "Cách diệt rêu tảo hại trong hồ cá với các loại thường gặp nhất Dưới đây là những loại tảo hại phổ biến và  cách diệt rêu tảo hại trong hồ cá không quá khó nhưng không phải đơn giản:<br> Tảo đốm: là những chấm tròn xanh xuất hiện trên mặt kính <br>thuộc nhóm Diatoms - tảo cát,<br> giúp cho tảo xanh phát triển phía trong.Loại ‘tảo’ này cực khó loại trừ và phải dùng 1 lưỡi lam bén để xử chúng. <br>Tảo sừng: giống như gạc nai thu nhỏ,<br> có màu xanh xám.Xuất hiện trên kính,<br> lọc và phụ kiện.Khó mà trị chúng bằng cơ học nên người ta thường dùng phương pháp hoá học. <br> Tảo sợi: có 2 loại chính: loại “tóc” thì ngắn hơn, <br> dài khoảng 5cm, <br> có xu hướng tạo thành từng đám.Loại “sợi” thì dài hơn nhiều, có thể tới 30cm, nguyên nhân là do thừa sắt trong nước.Cả hai loại đều dễ dàng loại bỏ bằng bàn chải răng. Cặn xanh: có 2 loại là “xù” và “lông”. Tảo “xù” không đáng lo ngại, kiểm soát bằng cách thả các loại cá ăn tảo.Loại ‘lông’ sợi rất dai, dài chừng 4mm và mọc dày như 1 mảng lông thú vậy, phải loại trừ bằng phương pháp cơ học. Cặn nâu: có bề mặt nhầy, bám trên lá cây, phụ kiện và kính. Thường xuất hiện khi cây cối kém phát triển do thiếu sáng. Có thể dễ dàng loại bỏ bằng cách chà rửa bề mặt. Nước xanh: phát sinh do dư ánh sáng.Bạn có thể sử dụng hệ thống lọc có than hoạt tính hoặc cát mịn để loại trừ chúng ra khỏi hồ.Loại tảo này là nguồn thức ăn tốt nhất cho các loại ấu trùng loài giáp xác như tôm tép",
        //        FootBlog = "Chia sẻ cách diệt rêu tảo hại trong hồ cá bằng các loài thủy sinh cảnh Cách diệt rêu tảo hại trong hồ cá hữu hiệu nhất đối với những người chơi cá cảnh lâu năm vẫn là cách tận dụng những đặc điểm sẵn có của các loài sinh vật được liệt kê dưới đây.Chúng sẽ giúp bạn dọn vệ sinh và giữ lại mật độ rêu phù hợp cho  Cá lau kính: Đây là một trong những loài cá ăn rêu tảo phổ biến nhất và có sẵn trên thị trường.Chúng có hình dáng nhìn rất hài hước, lớn đầu và mũi đẹp, có phần thân mập mạp, chiều dài cơ thể có thể đạt 10 - 15 cm. Chúng là loài ăn tạp đòi hỏi rất nhiều loại rêu tảo và lá cây, mọc ở phần đáy bể.Tuy nhiên nếu hết các loại rêu tảo để ăn chúng có thể ăn các loại lá mềm trong bể thủy sinh của bạn.</ p > Ốc Nerite: Đây là loài ăn rêu tảo tuyệt vời, có xọc vằn.Chúng có thể ăn tảo rêu có hại bám trên kính, trên lá cây và các loại dương xỉ.Giữ độ pH trên 7 để ốc có thể phát triển khỏe mạnh.</ p >  Ốc xoắn dẹt cỡ trung: Loại này thường ăn các cây rêu tảo bao phủ trên đá bể, trên kính hồ cá và các đồ trang trí khác.Chúng sẽ không bỏ qua mảnh vụn, trứng cá và thức ăn thừa. Bạn nên theo dõi nồng độ pH và giữ nước ở mức độ kiềm cứng thuận lợi(trên pH7) để đảm bảo rằng các ốc có đủ canxi để bảo trì vỏ và tăng trưởng.<br> Tép Amono Đây là một loài ăn rêu tảo rất phổ biến và hoạt động tích cực.Chúng là một trong những loài háu ăn, không chỉ ăn rêu tảo, mà còn ăn những cành cây mục đã chết và làm sạch các thức ăn thừa dưới đáy bể.Có thể nuôi chung với những loại cá nhỏ, hiền lành nhưng hoạt động nhanh nhẹn để không làm mồi cho chúng. Nhận biết tảo hại và biết cách diệt rêu tảo hại trong hồ cá  càng sớm càng tốt chính là biện pháp phòng tránh những nguyên nhân gây bệnh thường gặp ở các loài cá cảnh cũng như tránh được xung đột khi kết hợp chung nhiều loại rong tảo và cá khác. chúc các bạn thành công!",
        //         Type = "Hoca",
        //        TypeBlogs = n

        //    },
        //};
        //    List<Blog> BlogsAfterInsert = new List<Blog>();
        //    foreach (var blog in blogs)
        //    {
        //        BlogsAfterInsert.Add(context.Blogs.Add(blog));
        //    }
        //    context.SaveChanges();
            base.Seed(context);
        }
    }
}
